### ISSUE TITLE
Abbreviated tree view for phenotypes / diseases

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1339]
Warning: This is a non trivial ticket, but just capturing it as it has come up recently.

It would be nice to be able to view an entire phenotype profile according to its abbreviated hierarchy, whether affected anatomical region, or other relevant typing. The abbreviated tree would be nice to have in the following places:
- Phenogrid
- Phenotype tabs on disease pages 
- Phenotype tabs on gene pages
- Triptych

---
### Tasks:
- [ ] Decide on the upper-level phenotypic categories to display. Informed by HPO, Patient Archive, IMPC, JAX etc. It may make sense to find common ground among these categories where possible as user groups overlap and familiarity is probably worth striving for.
- [ ] Design how it should look on the front end
- [ ] Reality check mockups with users
- [ ] Create a corresponding Golr service (?) to serve the abbreviated tree
- [ ] Develop UI accordingly

**Comment by harryhoch** [comment]
@jmcmurry, some of this could be interesting for the patient-patient comparison as well, as we might want to compare patients along specific axes...

**Comment by jmcmurry** [comment]
Exactly; that was part of my thinking with the triptych :)

**Comment by jmcmurry** [comment]
Was researching a particular gene which associated with 5 diseases and I found myself wondering what these diseases have in common aside from this gene. How closely related are they? Do they involve similar pathways? It is impossible to do that kind of analysis easily right now, but the tree view might be part of the solution.

**Comment by mellybelly** [comment]
conversely, there is also no way to see the differences. For example, what are the non-matched phenotypes in the best matching diseases/models? no way to examine the differential diagnosis. a triptych view could help potentially but there should be some way to see them even in a hover over.
